[package]
name = "r02_compound_data_type"
version = "0.1.0"
authors = ["Sunil Pandey <inkingmind@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
